---
title: "TestSFManip"
author: "Craig O'Neill"
date: "April 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Library

```{r}
library(sf)
library(tidyverse)
```

##Load Spatial Data

```{r}
private_parcel <- st_read(dsn = ".",
                          layer = "Private_Parcels")

addresses <- private_parcel %>% 
  select(Planning, Master__35, Master__36, Improvem_1, Land.Value, Area_, Acres, Stand_Id, geometry)

colnames(addresses) <- c("ParcelID", "Addr1", "Addr2", "Improvement", "LandValue", "Area", "Acres", "PublicStand", "geometry")

na.omit(addresses)

addresses <- addresses %>% 
  mutate(Val = Improvement + LandValue)

```
Notes:  Could not pull in spatial data from a different drive (G drive for SS), would cause R to crash everytime.


#merging address with fire ignition risk
```{r}
fireignit <- read_csv("fireignitionrisk.csv")

colnames(fireignit) <- c("ParcelID", "GA25", "PA25")

addresses <- merge(addresses, fireignit, by = "ParcelID")
```

#merging address with hvra loss/severity info

```{r}
fireloss <- read_csv("HVRAseverityloss.csv")

colnames(fireloss) <- c("ParcelID", "NT_Loss", "Opt21_Loss")

addresses <- merge(addresses, fireloss, by = "ParcelID")

```

